#! /bin/sh

if ! test "x86_64" = "$(uname -m)"
then
    echo "incorrect host for test" 1>&2
    exit 1
fi

set -e
set -u

t=$1

cat $t

set -x

if ! ./cuik "$t"
then
    exit 1
fi

if ! "./a.exe" > "$t.output" 2>&1
then
    echo Bad exit code
    exit 1
fi

if ! diff -b -u "$t.expected" "$t.output"
then
    Bad diff
    exit 1
fi
